### PR TITLE
feat: add unit test for deleting code lists

### PR DESCRIPTION
**Pull request by EmmanuelDemey**

### CODE REVIEW

**Comment by EmmanuelDemey** [comment]
@BulotF I have just added few unit tests. And I found some issues on our code. THanks unit test :D 
I did not test the changes I made directly via the application, only from the unit test. 
Could you double check if everything is still fine ?

**Comment by BulotF** [comment]
I have a doubt about this line :
const childrenToUpdate = findParent(length => length > 1, currentNode);

Shouldn't it be ?
const childrenToUpdate = findParent(length => length - 1, currentNode);

**Comment by EmmanuelDemey** [comment]
I do not thing so. 
We check the size a the parents array, to get only children with more than 1 parent.

**Comment by BulotF** [comment]
I misread. It's fine now

**Pull request merged**
